### ISSUE TITLE
Repeating side navbar inner list elements 

### ISSUE THREAD

**Issue by rajeshvarma848** [start-angular/SB-Admin-BS4-Angular-2#48]
side navbar inner elements are appearing in the background please suggest me to resolve this issue
![capture](https://cloud.githubusercontent.com/assets/13297261/19181739/b0fe52f2-8c8c-11e6-872b-75c333b6ebd0.PNG)

Thanks,
Rajesh

**Comment by juananinca** [comment]
I had the same problem. Just edit your ` _app-base.scss` located in the `assets/sass/` folder as I show you:
```css
.nested-menu {
    .list-group-item {
        cursor: pointer;
    }
    .nested {
        list-style-type: none;
    }
    ul.submenu {
        height: 0;
    }
    & .expand {
        ul.submenu {
            list-style-type: none;
            height: auto;
            li {
                a {
                    color: #FFFFFF;
                    padding: 10px;
                    display: block;
                }
            }
        }
    }
  & .hidden {
    visibility: hidden;
  }
}
```
then you must edit each div menu in the typescript file `sidebar.ts` in the following way:
```typescript
<div class="nested-menu">
            <a class="list-group-item" (click)="addExpandClass('pages')">
                <span><i class="fa fa-plus"></i> &nbsp; Menu</span>
            </a>
            <li class="nested" [ngClass]="{'expand' : showMenu === 'pages',  hidden: showMenu !== 'pages' }">
                <ul class="submenu">
                    <li>
                        <a href><span>Submenu</span></a>
                    </li>
                    <li>
                        <a href><span>Submenu</span></a>
                    </li>
                </ul>
            </li>
        </div>
```

And that's all! :)
